In [1]:
from path import Path
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
file= Path('Resources/dataset.csv')
df= pd.read_csv(file)
df

,title,name,creator,art_series,price,symbol,type,likes,nsfw,tokens,year,rights,royalty,cid,path
0,30 min Drawings,Giant Frog,kristyglas,kristyglas_30-min-drawings_giant-frog,50.0,SWAP.HIVE,PHOTO,2,False,30,2020,1,0,QmegjZDN2gyD9A6cG4efj8DwbLLGTW6isDGadNC2yVJHfH,./dataset/image/QmegjZDN2gyD9A6cG4efj8DwbLLGTW...
1,Experimental Video,Biospecimens,juliakponsford,juliakponsford_experimental-video_biospecimens,500.0,SWAP.HIVE,VIDEO,0,False,1,2020,1,0,QmeN4KuTQwHPWvGDhiopNJziqmf1feGeabDD4Gk7z9DgUL,./dataset/video/QmeN4KuTQwHPWvGDhiopNJziqmf1fe...
2,Sexy Art,long legs,badsexy,badsexy_sexy-art_long-legs,10.0,SWAP.HIVE,PHOTO,0,True,2,2021,1,0,QmaifAjZTJd8jTxNrwSoGWmFpbPYcszMF4ZcZDBwpRR4v4,./dataset/image/QmaifAjZTJd8jTxNrwSoGWmFpbPYcs...
3,Dream World,A Guide in my Dreams,yoslehz,yoslehz_dream-world_a-guide-in-my-dreams,20.0,SWAP.HIVE,PHOTO,1,False,2,2020,1,0,QmUTicJApSyByFb7sgsNa6cz8MG5RKsHvGLP61gxSF3JsN,./dataset/image/QmUTicJApSyByFb7sgsNa6cz8MG5RK...
4,Dream World,Silent Observer,yoslehz,yoslehz_dream-world_silent-observer,20.0,SWAP.HIVE,GIF,0,False,2,2020,1,0,Qmb8WbXXdorG52sgY4mSyYUjevE65SGa2vhSxdXstfinz1,./dataset/gif/Qmb8WbXXdorG52sgY4mSyYUjevE65SGa...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4184,Abstract Erotica,Taste of Heaven,tntdabomb,tntdabomb_abstract-erotica_taste-of-heaven,50.0,SWAP.HIVE,PHOTO,0,False,10,2020,3,0,QmeNbzcYHKDzZFTuY3PqBPr5WGKMGmrjrTsKDKd7WTe422,./dataset/image/QmeNbzcYHKDzZFTuY3PqBPr5WGKMGm...
4185,GIF art,crypto thinkers,elgeko,elgeko_gif-art_crypto-thinkers,99.0,SWAP.HIVE,GIF,0,False,5,2020,1,0,QmQZDfsTyqH7uQe75NqeVmtzvNW9eN45hXpexekixeWM4F,./dataset/gif/QmQZDfsTyqH7uQe75NqeVmtzvNW9eN45...
4186,Eye,Eye Of The Beholder,rubenalexander,rubenalexander_eye_eye-of-the-beholder,50.0,SWAP.HIVE,PHOTO,0,False,3,2020,1,0,QmWTT58erwH6Vtv8UJNNM6mmWuwZNsWAYygRXmHnpJeeBa,./dataset/image/QmWTT58erwH6Vtv8UJNNM6mmWuwZNs...
4187,HIVE ART,online art - Cryptoverse,elgeko,elgeko_hive-art_online-art-cryptoverse,99.0,SWAP.HIVE,GIF,0,False,7,2020,1,0,QmSAFuLYMpkszCY45ednQpzjSYCpkpZzurygvWHCTP1yo9,./dataset/gif/QmSAFuLYMpkszCY45ednQpzjSYCpkpZz...
4188,fine arts - high resolution printable artworks,Dirty laundry in the fractal kitchen,elgeko,elgeko_fine-arts-high-resolution-printable-art...,700.0,SWAP.HIVE,PHOTO,0,False,1,2020,1,0,QmNYLy1vRaRYoGRMVmheRgMxPAcrUufoUJHFSe81DmzNB9,./dataset/image/QmNYLy1vRaRYoGRMVmheRgMxPAcrUu...

In [3]:
df_eda= df.copy()
df_eda

,title,name,creator,art_series,price,symbol,type,likes,nsfw,tokens,year,rights,royalty,cid,path
0,30 min Drawings,Giant Frog,kristyglas,kristyglas_30-min-drawings_giant-frog,50.0,SWAP.HIVE,PHOTO,2,False,30,2020,1,0,QmegjZDN2gyD9A6cG4efj8DwbLLGTW6isDGadNC2yVJHfH,./dataset/image/QmegjZDN2gyD9A6cG4efj8DwbLLGTW...
1,Experimental Video,Biospecimens,juliakponsford,juliakponsford_experimental-video_biospecimens,500.0,SWAP.HIVE,VIDEO,0,False,1,2020,1,0,QmeN4KuTQwHPWvGDhiopNJziqmf1feGeabDD4Gk7z9DgUL,./dataset/video/QmeN4KuTQwHPWvGDhiopNJziqmf1fe...
2,Sexy Art,long legs,badsexy,badsexy_sexy-art_long-legs,10.0,SWAP.HIVE,PHOTO,0,True,2,2021,1,0,QmaifAjZTJd8jTxNrwSoGWmFpbPYcszMF4ZcZDBwpRR4v4,./dataset/image/QmaifAjZTJd8jTxNrwSoGWmFpbPYcs...
3,Dream World,A Guide in my Dreams,yoslehz,yoslehz_dream-world_a-guide-in-my-dreams,20.0,SWAP.HIVE,PHOTO,1,False,2,2020,1,0,QmUTicJApSyByFb7sgsNa6cz8MG5RKsHvGLP61gxSF3JsN,./dataset/image/QmUTicJApSyByFb7sgsNa6cz8MG5RK...
4,Dream World,Silent Observer,yoslehz,yoslehz_dream-world_silent-observer,20.0,SWAP.HIVE,GIF,0,False,2,2020,1,0,Qmb8WbXXdorG52sgY4mSyYUjevE65SGa2vhSxdXstfinz1,./dataset/gif/Qmb8WbXXdorG52sgY4mSyYUjevE65SGa...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4184,Abstract Erotica,Taste of Heaven,tntdabomb,tntdabomb_abstract-erotica_taste-of-heaven,50.0,SWAP.HIVE,PHOTO,0,False,10,2020,3,0,QmeNbzcYHKDzZFTuY3PqBPr5WGKMGmrjrTsKDKd7WTe422,./dataset/image/QmeNbzcYHKDzZFTuY3PqBPr5WGKMGm...
4185,GIF art,crypto thinkers,elgeko,elgeko_gif-art_crypto-thinkers,99.0,SWAP.HIVE,GIF,0,False,5,2020,1,0,QmQZDfsTyqH7uQe75NqeVmtzvNW9eN45hXpexekixeWM4F,./dataset/gif/QmQZDfsTyqH7uQe75NqeVmtzvNW9eN45...
4186,Eye,Eye Of The Beholder,rubenalexander,rubenalexander_eye_eye-of-the-beholder,50.0,SWAP.HIVE,PHOTO,0,False,3,2020,1,0,QmWTT58erwH6Vtv8UJNNM6mmWuwZNsWAYygRXmHnpJeeBa,./dataset/image/QmWTT58erwH6Vtv8UJNNM6mmWuwZNs...
4187,HIVE ART,online art - Cryptoverse,elgeko,elgeko_hive-art_online-art-cryptoverse,99.0,SWAP.HIVE,GIF,0,False,7,2020,1,0,QmSAFuLYMpkszCY45ednQpzjSYCpkpZzurygvWHCTP1yo9,./dataset/gif/QmSAFuLYMpkszCY45ednQpzjSYCpkpZz...
4188,fine arts - high resolution printable artworks,Dirty laundry in the fractal kitchen,elgeko,elgeko_fine-arts-high-resolution-printable-art...,700.0,SWAP.HIVE,PHOTO,0,False,1,2020,1,0,QmNYLy1vRaRYoGRMVmheRgMxPAcrUufoUJHFSe81DmzNB9,./dataset/image/QmNYLy1vRaRYoGRMVmheRgMxPAcrUu...

In [4]:
df_eda['symbol'].value_counts()

SWAP.HIVE    4189
Name: symbol, dtype: int64

In [5]:
df_eda['name'].value_counts()

Sunset                                                        3
Unicorn                                                       3
Genesis Tree Crying Leaves                                    2
opensea                                                       2
Angel                                                         2
                                                             ..
ðŸ”³ Black Square" by Daria Yakubenko ðŸ–¤ From Malevich's idea"    1
UNCLAsSIFI3D                                                  1
Mirror Plasma                                                 1
pleasure                                                      1
Posted                                                        1
Name: name, Length: 4084, dtype: int64

In [6]:
df_eda['title'].value_counts()

Trash for Life (In the Haunted Honeycomb)    90
doze                                         57
REKT                                         43
Gif                                          41
Portraits                                    37
                                             ..
Annette1                                      1
Haunted House                                 1
Poetry                                        1
Star hope                                     1
Blued Buddha                                  1
Name: title, Length: 1715, dtype: int64

In [7]:
df_eda['creator'].value_counts()

elenasteem         170
richardfyates      119
artxmike            99
doze                93
elgeko              88
                  ...
athomewithcraig      1
artplusbrad          1
ooakosimo            1
derflow              1
cybershakti          1
Name: creator, Length: 515, dtype: int64

In [8]:
df_eda['art_series'].value_counts()

svdsdragunov_demise_icon-of-the-inquisition     2
bardionson_lines-of-light_neon-gasmask-alert    2
rubenalexander_eye_eye-of-the-beholder          2
oddballgraphics_light-painting_hive-on          2
elgeko_visual-art_hexa-tetra                    2
                                               ..
newmanbra_new_movie-star                        1
tomlovesid_tomlovesid_faces-002                 1
barbarabezina_gif_before-sunrise                1
aleister_machiavellian_unknown-temperament      1
rektdoteth_rekt_dark-forest-still               1
Name: art_series, Length: 4120, dtype: int64

In [9]:
df_eda= df_eda.drop(columns=['cid','path','symbol', 'name','title','art_series'])
df_eda

,creator,price,type,likes,nsfw,tokens,year,rights,royalty
0,kristyglas,50.0,PHOTO,2,False,30,2020,1,0
1,juliakponsford,500.0,VIDEO,0,False,1,2020,1,0
2,badsexy,10.0,PHOTO,0,True,2,2021,1,0
3,yoslehz,20.0,PHOTO,1,False,2,2020,1,0
4,yoslehz,20.0,GIF,0,False,2,2020,1,0
...,...,...,...,...,...,...,...,...,...
4184,tntdabomb,50.0,PHOTO,0,False,10,2020,3,0
4185,elgeko,99.0,GIF,0,False,5,2020,1,0
4186,rubenalexander,50.0,PHOTO,0,False,3,2020,1,0
4187,elgeko,99.0,GIF,0,False,7,2020,1,0
4188,elgeko,700.0,PHOTO,0,False,1,2020,1,0

In [10]:
df_eda.dtypes

creator     object
price      float64
type        object
likes        int64
nsfw          bool
tokens       int64
year         int64
rights       int64
royalty      int64
dtype: object

In [11]:
df_eda['price'].value_counts()

50.0      358
100.0     261
25.0      211
30.0      191
150.0     173
         ...
365.0       1
279.0       1
249.0       1
195.0       1
5200.0      1
Name: price, Length: 328, dtype: int64

In [12]:
results= []
for x in df_eda.price:
    if x > 1000:
        results.append(2)
    elif x>100:
        results.append(1)
    else:
        results.append(0)
df_eda['price_category']=results
df_eda.head()

,creator,price,type,likes,nsfw,tokens,year,rights,royalty,price_category
0,kristyglas,50.0,PHOTO,2,False,30,2020,1,0,0
1,juliakponsford,500.0,VIDEO,0,False,1,2020,1,0,1
2,badsexy,10.0,PHOTO,0,True,2,2021,1,0,0
3,yoslehz,20.0,PHOTO,1,False,2,2020,1,0,0
4,yoslehz,20.0,GIF,0,False,2,2020,1,0,0

In [13]:
df_eda_encoded= pd.get_dummies(df_eda, columns=['creator','nsfw', 'type', 'year'])
df_eda_encoded

,price,likes,tokens,rights,royalty,price_category,creator_a-u-m,creator_a1-shroom-spores,creator_aagabriel,creator_adamfryda-art,...,year_2014,year_2015,year_2016,year_2017,year_2018,year_2019,year_2020,year_2021,year_2112,year_2578
0,50.0,2,30,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,500.0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,10.0,0,2,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,20.0,1,2,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,20.0,0,2,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4184,50.0,0,10,3,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4185,99.0,0,5,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4186,50.0,0,3,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4187,99.0,0,7,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4188,700.0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [14]:
df_eda_encoded.dtypes

price        float64
likes          int64
tokens         int64
rights         int64
royalty        int64
              ...
year_2019      uint8
year_2020      uint8
year_2021      uint8
year_2112      uint8
year_2578      uint8
Length: 559, dtype: object