In [1]:
from path import Path
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
file= Path('Resources/dataset.csv')
df= pd.read_csv(file)
df

,title,name,creator,art_series,price,symbol,type,likes,nsfw,tokens,year,rights,royalty,cid,path
0,30 min Drawings,Giant Frog,kristyglas,kristyglas_30-min-drawings_giant-frog,50.0,SWAP.HIVE,PHOTO,2,False,30,2020,1,0,QmegjZDN2gyD9A6cG4efj8DwbLLGTW6isDGadNC2yVJHfH,./dataset/image/QmegjZDN2gyD9A6cG4efj8DwbLLGTW...
1,Experimental Video,Biospecimens,juliakponsford,juliakponsford_experimental-video_biospecimens,500.0,SWAP.HIVE,VIDEO,0,False,1,2020,1,0,QmeN4KuTQwHPWvGDhiopNJziqmf1feGeabDD4Gk7z9DgUL,./dataset/video/QmeN4KuTQwHPWvGDhiopNJziqmf1fe...
2,Sexy Art,long legs,badsexy,badsexy_sexy-art_long-legs,10.0,SWAP.HIVE,PHOTO,0,True,2,2021,1,0,QmaifAjZTJd8jTxNrwSoGWmFpbPYcszMF4ZcZDBwpRR4v4,./dataset/image/QmaifAjZTJd8jTxNrwSoGWmFpbPYcs...
3,Dream World,A Guide in my Dreams,yoslehz,yoslehz_dream-world_a-guide-in-my-dreams,20.0,SWAP.HIVE,PHOTO,1,False,2,2020,1,0,QmUTicJApSyByFb7sgsNa6cz8MG5RKsHvGLP61gxSF3JsN,./dataset/image/QmUTicJApSyByFb7sgsNa6cz8MG5RK...
4,Dream World,Silent Observer,yoslehz,yoslehz_dream-world_silent-observer,20.0,SWAP.HIVE,GIF,0,False,2,2020,1,0,Qmb8WbXXdorG52sgY4mSyYUjevE65SGa2vhSxdXstfinz1,./dataset/gif/Qmb8WbXXdorG52sgY4mSyYUjevE65SGa...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4184,Abstract Erotica,Taste of Heaven,tntdabomb,tntdabomb_abstract-erotica_taste-of-heaven,50.0,SWAP.HIVE,PHOTO,0,False,10,2020,3,0,QmeNbzcYHKDzZFTuY3PqBPr5WGKMGmrjrTsKDKd7WTe422,./dataset/image/QmeNbzcYHKDzZFTuY3PqBPr5WGKMGm...
4185,GIF art,crypto thinkers,elgeko,elgeko_gif-art_crypto-thinkers,99.0,SWAP.HIVE,GIF,0,False,5,2020,1,0,QmQZDfsTyqH7uQe75NqeVmtzvNW9eN45hXpexekixeWM4F,./dataset/gif/QmQZDfsTyqH7uQe75NqeVmtzvNW9eN45...
4186,Eye,Eye Of The Beholder,rubenalexander,rubenalexander_eye_eye-of-the-beholder,50.0,SWAP.HIVE,PHOTO,0,False,3,2020,1,0,QmWTT58erwH6Vtv8UJNNM6mmWuwZNsWAYygRXmHnpJeeBa,./dataset/image/QmWTT58erwH6Vtv8UJNNM6mmWuwZNs...
4187,HIVE ART,online art - Cryptoverse,elgeko,elgeko_hive-art_online-art-cryptoverse,99.0,SWAP.HIVE,GIF,0,False,7,2020,1,0,QmSAFuLYMpkszCY45ednQpzjSYCpkpZzurygvWHCTP1yo9,./dataset/gif/QmSAFuLYMpkszCY45ednQpzjSYCpkpZz...
4188,fine arts - high resolution printable artworks,Dirty laundry in the fractal kitchen,elgeko,elgeko_fine-arts-high-resolution-printable-art...,700.0,SWAP.HIVE,PHOTO,0,False,1,2020,1,0,QmNYLy1vRaRYoGRMVmheRgMxPAcrUufoUJHFSe81DmzNB9,./dataset/image/QmNYLy1vRaRYoGRMVmheRgMxPAcrUu...

In [16]:
df.dtypes

title          object
name           object
creator        object
art_series     object
price         float64
symbol         object
type           object
likes           int64
nsfw             bool
tokens          int64
year            int64
rights          int64
royalty         int64
cid            object
path           object
dtype: object

In [3]:
df_eda= df.copy()
df_eda

,title,name,creator,art_series,price,symbol,type,likes,nsfw,tokens,year,rights,royalty,cid,path
0,30 min Drawings,Giant Frog,kristyglas,kristyglas_30-min-drawings_giant-frog,50.0,SWAP.HIVE,PHOTO,2,False,30,2020,1,0,QmegjZDN2gyD9A6cG4efj8DwbLLGTW6isDGadNC2yVJHfH,./dataset/image/QmegjZDN2gyD9A6cG4efj8DwbLLGTW...
1,Experimental Video,Biospecimens,juliakponsford,juliakponsford_experimental-video_biospecimens,500.0,SWAP.HIVE,VIDEO,0,False,1,2020,1,0,QmeN4KuTQwHPWvGDhiopNJziqmf1feGeabDD4Gk7z9DgUL,./dataset/video/QmeN4KuTQwHPWvGDhiopNJziqmf1fe...
2,Sexy Art,long legs,badsexy,badsexy_sexy-art_long-legs,10.0,SWAP.HIVE,PHOTO,0,True,2,2021,1,0,QmaifAjZTJd8jTxNrwSoGWmFpbPYcszMF4ZcZDBwpRR4v4,./dataset/image/QmaifAjZTJd8jTxNrwSoGWmFpbPYcs...
3,Dream World,A Guide in my Dreams,yoslehz,yoslehz_dream-world_a-guide-in-my-dreams,20.0,SWAP.HIVE,PHOTO,1,False,2,2020,1,0,QmUTicJApSyByFb7sgsNa6cz8MG5RKsHvGLP61gxSF3JsN,./dataset/image/QmUTicJApSyByFb7sgsNa6cz8MG5RK...
4,Dream World,Silent Observer,yoslehz,yoslehz_dream-world_silent-observer,20.0,SWAP.HIVE,GIF,0,False,2,2020,1,0,Qmb8WbXXdorG52sgY4mSyYUjevE65SGa2vhSxdXstfinz1,./dataset/gif/Qmb8WbXXdorG52sgY4mSyYUjevE65SGa...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4184,Abstract Erotica,Taste of Heaven,tntdabomb,tntdabomb_abstract-erotica_taste-of-heaven,50.0,SWAP.HIVE,PHOTO,0,False,10,2020,3,0,QmeNbzcYHKDzZFTuY3PqBPr5WGKMGmrjrTsKDKd7WTe422,./dataset/image/QmeNbzcYHKDzZFTuY3PqBPr5WGKMGm...
4185,GIF art,crypto thinkers,elgeko,elgeko_gif-art_crypto-thinkers,99.0,SWAP.HIVE,GIF,0,False,5,2020,1,0,QmQZDfsTyqH7uQe75NqeVmtzvNW9eN45hXpexekixeWM4F,./dataset/gif/QmQZDfsTyqH7uQe75NqeVmtzvNW9eN45...
4186,Eye,Eye Of The Beholder,rubenalexander,rubenalexander_eye_eye-of-the-beholder,50.0,SWAP.HIVE,PHOTO,0,False,3,2020,1,0,QmWTT58erwH6Vtv8UJNNM6mmWuwZNsWAYygRXmHnpJeeBa,./dataset/image/QmWTT58erwH6Vtv8UJNNM6mmWuwZNs...
4187,HIVE ART,online art - Cryptoverse,elgeko,elgeko_hive-art_online-art-cryptoverse,99.0,SWAP.HIVE,GIF,0,False,7,2020,1,0,QmSAFuLYMpkszCY45ednQpzjSYCpkpZzurygvWHCTP1yo9,./dataset/gif/QmSAFuLYMpkszCY45ednQpzjSYCpkpZz...
4188,fine arts - high resolution printable artworks,Dirty laundry in the fractal kitchen,elgeko,elgeko_fine-arts-high-resolution-printable-art...,700.0,SWAP.HIVE,PHOTO,0,False,1,2020,1,0,QmNYLy1vRaRYoGRMVmheRgMxPAcrUufoUJHFSe81DmzNB9,./dataset/image/QmNYLy1vRaRYoGRMVmheRgMxPAcrUu...

In [4]:
df_eda['symbol'].value_counts()

SWAP.HIVE    4189
Name: symbol, dtype: int64

In [5]:
df_eda['name'].value_counts()

Unicorn                                  3
Sunset                                   3
Hexa Tetra II                            2
The Vixen                                2
Angel                                    2
                                        ..
Forceoperator                            1
Rune NG                                  1
Zen Pepeception (collab with el geko)    1
Lovely Rose                              1
water mandala                            1
Name: name, Length: 4084, dtype: int64

In [6]:
df_eda['title'].value_counts()

Trash for Life (In the Haunted Honeycomb)         90
doze                                              57
REKT                                              43
Gif                                               41
Portraits                                         37
                                                  ..
Digital Beer Labels                                1
let's see what the muses of 2021 have to offer     1
Little owlet SAI                                   1
MUSICOS                                            1
Afterworld                                         1
Name: title, Length: 1715, dtype: int64

In [7]:
df_eda['creator'].value_counts()

elenasteem       170
richardfyates    119
artxmike          99
doze              93
elgeko            88
                ...
polarmystro        1
vviz               1
fabiyamada         1
enrique89          1
x-numismatik       1
Name: creator, Length: 515, dtype: int64

In [8]:
df_eda['art_series'].value_counts()

elenasteem_neytiri-is-a-character-from-the-movie-avatar_neytiri-is-a-character-from-the-movie-avatar    2
a1-shroom-spores_portraits_hempfest-portrait                                                            2
borjan_jokes-metaphors-fantasies_hanging-mystery                                                        2
opidia_illumination_above                                                                               2
rubenalexander_mouse-fetish_marble-triple-click                                                         2
                                                                                                       ..
starmasayume_prismacolor-chibi_avariel-sister-of-ice                                                    1
andrianna_raccoon-is-ready-for-the-new-year_raccoon-is-ready-for-the-new-year                           1
gmncy_quarantine-spring_quarantine-spring-loop-1                                                        1
rektdoteth_rekt_hand-of-satoshi                                                                         1
secondrealm_summer-in-the-city_untitled-vi                                                              1
Name: art_series, Length: 4120, dtype: int64

In [9]:
df_eda.dtypes

title          object
name           object
creator        object
art_series     object
price         float64
symbol         object
type           object
likes           int64
nsfw             bool
tokens          int64
year            int64
rights          int64
royalty         int64
cid            object
path           object
dtype: object

In [10]:
df_eda['type'].value_counts()

PHOTO    3071
GIF       665
VIDEO     453
Name: type, dtype: int64

In [11]:
results= []
for x in df_eda.type:
    if x == "PHOTO":
        results.append(2)
    elif x == "GIF":
        results.append(1)
    else:
        results.append(0)
df_eda['type_category']=results
df_eda.head()

,title,name,creator,art_series,price,symbol,type,likes,nsfw,tokens,year,rights,royalty,cid,path,type_category
0,30 min Drawings,Giant Frog,kristyglas,kristyglas_30-min-drawings_giant-frog,50.0,SWAP.HIVE,PHOTO,2,False,30,2020,1,0,QmegjZDN2gyD9A6cG4efj8DwbLLGTW6isDGadNC2yVJHfH,./dataset/image/QmegjZDN2gyD9A6cG4efj8DwbLLGTW...,2
1,Experimental Video,Biospecimens,juliakponsford,juliakponsford_experimental-video_biospecimens,500.0,SWAP.HIVE,VIDEO,0,False,1,2020,1,0,QmeN4KuTQwHPWvGDhiopNJziqmf1feGeabDD4Gk7z9DgUL,./dataset/video/QmeN4KuTQwHPWvGDhiopNJziqmf1fe...,0
2,Sexy Art,long legs,badsexy,badsexy_sexy-art_long-legs,10.0,SWAP.HIVE,PHOTO,0,True,2,2021,1,0,QmaifAjZTJd8jTxNrwSoGWmFpbPYcszMF4ZcZDBwpRR4v4,./dataset/image/QmaifAjZTJd8jTxNrwSoGWmFpbPYcs...,2
3,Dream World,A Guide in my Dreams,yoslehz,yoslehz_dream-world_a-guide-in-my-dreams,20.0,SWAP.HIVE,PHOTO,1,False,2,2020,1,0,QmUTicJApSyByFb7sgsNa6cz8MG5RKsHvGLP61gxSF3JsN,./dataset/image/QmUTicJApSyByFb7sgsNa6cz8MG5RK...,2
4,Dream World,Silent Observer,yoslehz,yoslehz_dream-world_silent-observer,20.0,SWAP.HIVE,GIF,0,False,2,2020,1,0,Qmb8WbXXdorG52sgY4mSyYUjevE65SGa2vhSxdXstfinz1,./dataset/gif/Qmb8WbXXdorG52sgY4mSyYUjevE65SGa...,1

In [12]:
df_eda= df_eda.drop(columns=['type','cid','path','symbol', 'name','title','art_series'])
df_eda

,creator,price,likes,nsfw,tokens,year,rights,royalty,type_category
0,kristyglas,50.0,2,False,30,2020,1,0,2
1,juliakponsford,500.0,0,False,1,2020,1,0,0
2,badsexy,10.0,0,True,2,2021,1,0,2
3,yoslehz,20.0,1,False,2,2020,1,0,2
4,yoslehz,20.0,0,False,2,2020,1,0,1
...,...,...,...,...,...,...,...,...,...
4184,tntdabomb,50.0,0,False,10,2020,3,0,2
4185,elgeko,99.0,0,False,5,2020,1,0,1
4186,rubenalexander,50.0,0,False,3,2020,1,0,2
4187,elgeko,99.0,0,False,7,2020,1,0,1
4188,elgeko,700.0,0,False,1,2020,1,0,2

In [13]:
df_eda_encoded= pd.get_dummies(df_eda, columns=['creator','nsfw','year'])
df_eda_encoded

,price,likes,tokens,rights,royalty,type_category,creator_a-u-m,creator_a1-shroom-spores,creator_aagabriel,creator_adamfryda-art,...,year_2014,year_2015,year_2016,year_2017,year_2018,year_2019,year_2020,year_2021,year_2112,year_2578
0,50.0,2,30,1,0,2,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,500.0,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,10.0,0,2,1,0,2,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,20.0,1,2,1,0,2,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,20.0,0,2,1,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4184,50.0,0,10,3,0,2,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4185,99.0,0,5,1,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4186,50.0,0,3,1,0,2,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4187,99.0,0,7,1,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4188,700.0,0,1,1,0,2,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [14]:
new_df= df_eda_encoded.sample(n=1500)
new_df

,price,likes,tokens,rights,royalty,type_category,creator_a-u-m,creator_a1-shroom-spores,creator_aagabriel,creator_adamfryda-art,...,year_2014,year_2015,year_2016,year_2017,year_2018,year_2019,year_2020,year_2021,year_2112,year_2578
3212,50.0,0,1,1,0,2,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
171,40.0,2,2,1,0,2,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3362,50.0,0,5,1,0,2,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
974,8.0,1,2,1,0,2,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4074,60.0,0,4,1,0,2,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4012,50.0,0,1,3,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
459,20.0,0,2,1,0,2,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1828,85.0,0,5,1,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2171,299.0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3549,47.0,0,5,3,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [15]:
new_df['type_category'].value_counts()

2    1090
1     251
0     159
Name: type_category, dtype: int64